### PR TITLE
Enable semmc tests

### PR DESCRIPTION
**Pull request by LisannaAtGalois**

### CODE REVIEW

**Comment by LisannaAtGalois** [comment]
The build of the tests for semmc are failing in semmc/tests/ParamFormulaTests.hs in several instances: https://github.com/GaloisInc/semmc/pull/57/checks?check_run_id=1300418260#step:7:1168

**Comment by travitch** [comment]
Thanks for the note - I can fix that

**Comment by travitch** [comment]
Should be fixed by #61 - if that works feel free to merge it or just cherry pick the commit into this PR

**Review by kquick — APPROVED** [review]
Looks like Tristan's changes fix the builds and this should be good, thanks!

**Comment by LisannaAtGalois** [comment]
> Should be fixed by #61 - if that works feel free to merge it or just cherry pick the commit into this PR

@travitch Thanks for the patch, looks like some of the tests are failing: https://github.com/GaloisInc/semmc/pull/57/checks?check_run_id=1354557091#step:10:74

**Comment by travitch** [comment]
I have a fix for what4-serialize that implements the missing `bvFill` operation. Once I merge that, the tests pass (on my machine). Just waiting for CI to pass on that repo.

**Comment by travitch** [comment]
Okay, the what4-serialize fix is merged into that repo. The semmc tests pass on my machine with that change.

**Pull request merged**
